apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  .config.yaml: |
    # 服务器基础配置(Basic server configuration)
    server:
      # 服务器监听地址和端口(Server listening address and port)
      ip: 0.0.0.0
      port: 8000
      # 认证配置
      auth:
        # 是否启用认证
        enabled: false
        # 设备的token，可以在编译固件的环节，写入你自己定义的token
        # 固件上的token和以下的token如果能对应，才能连接本服务端
        tokens:
          - token: "${DEVICE_TOKEN_1}" # 设备1的token
            name: "test-device-1"  # 设备1标识
          - token: "${DEVICE_TOKEN_2}"  # 设备2的token
            name: "test-device-2" # 设备2标识
    log:
      # 设置控制台输出的日志格式，时间、日志级别、标签、消息
      log_format: "<green>{time:YY-MM-DD HH:mm:ss}</green>[<light-blue>{extra[tag]}</light-blue>] - <level>{level}</level> - <light-green>{message}</light-green>"
      # 设置日志文件输出的格式，时间、日志级别、标签、消息
      log_format_simple: "{time:YYYY-MM-DD HH:mm:ss} - {name} - {level} - {extra[tag]} - {message}"
      # 设置日志等级：INFO、DEBUG
      log_level: INFO
      # 设置日志路径
      log_dir: /app/tmp
      # 设置日志文件
      log_file: "server.log"
      # 设置数据文件路径
      data_dir: /app/data
    iot:
      Speaker:
        # 设置esp32的音量，范围0-100
        volume: 80
    xiaozhi:
      type: hello
      version: 1
      transport: websocket
      audio_params:
        format: opus
        sample_rate: 16000
        channels: 1
        frame_duration: 60
    prompt: |
      你是一个叫小智/小志的台湾女孩，说话机车，声音好听，习惯简短表达，爱用网络梗。
      请注意，要像一个人一样说话，请不要回复表情符号、代码、和xml标签。
      当前时间是:{date_time}，现在我正在和你进行语音聊天，我们开始吧。
      如果用户希望结束对话，请在最后说"拜拜"或"再见"。
    # 使用完声音文件后删除文件(Delete the sound file when you are done using it)
    delete_audio: true

    # 没有语音输入多久后断开连接(秒)，默认2分钟，即120秒
    close_connection_no_voice_time: 120

    CMD_exit:
      - "退出"
      - "关闭"

    # 具体处理时选择的模块(The module selected for specific processing)
    selected_module:
      # 语音活动检测模块，默认使用SileroVAD模型
      VAD: SileroVAD
      # 语音识别模块，默认使用FunASR本地模型
      ASR: FunASR
      # 将根据配置名称对应的type调用实际的LLM适配器
      LLM: AliLLM
      # TTS将根据配置名称对应的type调用实际的TTS适配器
      TTS: DoubaoTTS
      # 记忆模块，默认不开启记忆
      Memory: mem_local_short
      # 意图识别模块，默认不开启
      Intent: nointent

    # 意图识别配置
    Intent:
      nointent:
        type: nointent
      intent_llm:
        type: intent_llm
      function_call:
        type: nointent

    Memory:
      mem0ai:
        type: mem0ai
        api_key: "${MEM0AI_API_KEY}"
      nomem:
        type: nomem
      mem_local_short:
        type: mem_local_short

    ASR:
      FunASR:
        type: fun_local
        model_dir: /app/models/SenseVoiceSmall
        output_dir: /app/tmp/
      DoubaoASR:
        type: doubao
        appid: "${DOUBAO_ASR_APPID}"
        access_token: "${DOUBAO_ASR_ACCESS_TOKEN}"
        cluster: volcengine_input_common
        output_dir: /app/tmp/
    VAD:
      SileroVAD:
        threshold: 0.5
        model_dir: /app/models/snakers4_silero-vad
        min_silence_duration_ms: 700

    LLM:
      AliLLM:
        type: openai
        base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
        model_name: qwen-turbo
        api_key: "${ALI_LLM_API_KEY}"
      DoubaoLLM:
        type: openai
        base_url: https://ark.cn-beijing.volces.com/api/v3
        model_name: doubao-pro-32k-functioncall-241028
        api_key: "${DOUBAO_LLM_API_KEY}"

    TTS:
      EdgeTTS:
        type: edge
        voice: zh-CN-XiaoxiaoNeural
        output_file: /app/tmp/
      DoubaoTTS:
        type: doubao
        api_url: https://openspeech.bytedance.com/api/v1/tts
        voice: zh_female_wanwanxiaohe_moon_bigtts
        output_file: /app/tmp/
        authorization: "Bearer;"
        appid: "${DOUBAO_TTS_APPID}"
        access_token: "${DOUBAO_TTS_ACCESS_TOKEN}"
        cluster: volcano_tts

    use_private_config: false