apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
spec:
  template:
    metadata:
      annotations:
        environment: "staging"
        cluster: "shared-app-cluster"
    spec:
      serviceAccountName: staging-default
      # 这里是其他可能的配置 