apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-server-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/backend-config: |
      {
        "default": "websocket-backend-config"
      }
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: websocket-server
            port:
              number: 80