apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging
namePrefix: staging-

resources:
- ../../base
- pvc.yaml

patches:
- path: configmap.yaml
  target:
    kind: ConfigMap
    name: app-config
- path: deployment-annotations.yaml
  target:
    kind: Deployment
    name: app-server
- path: deployment-resource-limits.yaml
  target:
    kind: Deployment
    name: app-server

images:
- name: app-server
  newName: REGISTRY_PATH
  newTag: latest

commonAnnotations:
  # 这些注解会被添加到所有资源
  app.kubernetes.io/environment: staging 