apiVersion: v1
kind: ServiceAccount
metadata:
  name: staging-default
  namespace: staging
  annotations:
    iam.gke.io/gcp-service-account: shared-gke-node-sa@rare-attic-453703-a8.iam.gserviceaccount.com 