apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  annotations:
    app.kubernetes.io/environment: staging
    cloud.google.com/app-protocols: '{"websocket":"HTTP"}'
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: ClusterIP
  ports:
  - name: websocket
    port: 80
    targetPort: websocket
    protocol: TCP
  selector:
    app: websocket-server 