apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-

resources:
- ../../base
- ingress.yaml

patches:
- path: configmap.yaml
  target:
    kind: ConfigMap
    name: app-config
- path: deployment.yaml
  target:
    kind: Deployment
    name: app-server
- path: deployment-ha.yaml
  target:
    kind: Deployment
    name: app-server

images:
- name: app-server
  newName: REGISTRY_PATH
  newTag: stable 