# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket      = "tfstate-rare-attic"
    credentials = "/Users/fangyuedong/workspace/github/ai-buddy/devops/environments/staging/../../../service-account.json"
    prefix      = "."
  }
}
