# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.10"
    }
  }
}

provider "google" {
  project     = var.project_id
  region      = var.region
  credentials = file("/Users/fangyuedong/workspace/github/ai-buddy/devops/environments/staging/../../../service-account.json")
}
