"""add child and buddy tables

Revision ID: 3a5b78f29c4e
Revises: 2d6005813fd9
Create Date: 2025-05-01 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5b78f29c4e'
down_revision = '2d6005813fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 children 表
    op.create_table('children',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('gender', sa.String(length=16), nullable=False),
        sa.Column('age', sa.Float(), nullable=False),
        sa.Column('interests', sa.JSON(), nullable=True),
        sa.Column('avatar_path', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建 buddies 表
    op.create_table('buddies',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('child_id', sa.String(length=36), nullable=True),
        sa.Column('avatar_path', sa.String(length=255), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('abilities', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['child_id'], ['children.id'], )
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除表的顺序很重要，先删除有外键依赖的表
    op.drop_table('buddies')
    op.drop_table('children')
    
    # ### end Alembic commands ### 