"""add dialogues usages resources tables

Revision ID: 4b7e89f34d5f
Revises: 3a5b78f29c4e
Create Date: 2025-05-01 23:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7e89f34d5f'
down_revision = '3a5b78f29c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 resources 表
    op.create_table('resources',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('type', sa.String(length=32), nullable=False),
        sa.Column('title', sa.String(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('url', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建 dialogues 表
    op.create_table('dialogues',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('child_id', sa.String(length=36), nullable=False),
        sa.Column('buddy_id', sa.String(length=36), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
        sa.ForeignKeyConstraint(['buddy_id'], ['buddies.id'], )
    )
    
    # 创建 usages 表
    op.create_table('usages',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('child_id', sa.String(length=36), nullable=False),
        sa.Column('buddy_id', sa.String(length=36), nullable=False),
        sa.Column('type', sa.String(length=32), nullable=False),
        sa.Column('duration', sa.Float(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
        sa.ForeignKeyConstraint(['buddy_id'], ['buddies.id'], )
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除表的顺序很重要，先删除有外键依赖的表
    op.drop_table('usages')
    op.drop_table('dialogues')
    op.drop_table('resources')
    
    # ### end Alembic commands ### 