
"""add child and buddy

Revision ID: cc8728c03b39
Revises: 2d6005813fd9
Create Date: 2025-05-01 22:52:52.348634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8728c03b39'
down_revision = '2d6005813fd9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###