apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: websocket-server
data:
  APP_ENV: "base"
  LOG_LEVEL: "INFO"
  MAX_CONNECTIONS: "500"
  MODEL_PATH: "/app/models"
  MODEL_REVISION: "latest"
  HUGGINGFACE_REPO_ID: "FunAudioLLM/SenseVoiceSmall" 