apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
spec:
  template:
    metadata:
      annotations:
        # 这些是基础注解，会被环境特定的注解覆盖或合并
        app.kubernetes.io/managed-by: "github-actions"
        app.kubernetes.io/part-of: "ai-buddy" 