apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  labels:
    app: websocket-server
spec:
  selector:
    app: websocket-server
  ports:
  - name: ws
    port: 8080
    targetPort: 8000
  type: ClusterIP 